use('insurance')

db.t_client.insertMany([
  {
    client_id: 1,
    first_name: "Александр",
    last_name: "Иванов",
    middle_name: "Сергеевич",
    email: "ivanov.a1@mail.ru",
    phone_number: "+7 900 000-00-01",
  },
  {
    client_id: 2,
    first_name: "Мария",
    last_name: "Петрова",
    middle_name: "Андреевна",
    email: "petrova.m2@mail.ru",
    phone_number: "+7 900 000-00-02",
  },
  {
    client_id: 3,
    first_name: "Дмитрий",
    last_name: "Сидоров",
    middle_name: "Викторович",
    email: "sidorov.d3@mail.ru",
    phone_number: "+7 900 000-00-03",
  },
  {
    client_id: 4,
    first_name: "Елена",
    last_name: "Кузнецова",
    middle_name: "Олеговна",
    email: "kuznetsova.e4@mail.ru",
    phone_number: "+7 900 000-00-04",
  },
  {
    client_id: 5,
    first_name: "Артём",
    last_name: "Смирнов",
    middle_name: "Игоревич",
    email: "smirnov.a5@mail.ru",
    phone_number: "+7 900 000-00-05",
  },
  {
    client_id: 6,
    first_name: "Ольга",
    last_name: "Попова",
    middle_name: "Романовна",
    email: "popova.o6@mail.ru",
    phone_number: "+7 900 000-00-06",
  },
  {
    client_id: 7,
    first_name: "Максим",
    last_name: "Васильев",
    middle_name: "Денисович",
    email: "vasiliev.m7@mail.ru",
    phone_number: "+7 900 000-00-07",
  },
  {
    client_id: 8,
    first_name: "Анна",
    last_name: "Новикова",
    middle_name: "Павловна",
    email: "novikova.a8@mail.ru",
    phone_number: "+7 900 000-00-08",
  },
  {
    client_id: 9,
    first_name: "Илья",
    last_name: "Фёдоров",
    middle_name: "Михайлович",
    email: "fedorov.i9@mail.ru",
    phone_number: "+7 900 000-00-09",
  },
  {
    client_id: 10,
    first_name: "Татьяна",
    last_name: "Морозова",
    middle_name: "Сергеевна",
    email: "morozova.t10@mail.ru",
    phone_number: "+7 900 000-00-10",
  },
  {
    client_id: 11,
    first_name: "Никита",
    last_name: "Волков",
    middle_name: "Алексеевич",
    email: "volkov.n11@mail.ru",
    phone_number: "+7 900 000-00-11",
  },
  {
    client_id: 12,
    first_name: "Юлия",
    last_name: "Алексеева",
    middle_name: "Владимировна",
    email: "alekseeva.y12@mail.ru",
    phone_number: "+7 900 000-00-12",
  },
  {
    client_id: 13,
    first_name: "Владимир",
    last_name: "Лебедев",
    middle_name: "Степанович",
    email: "lebedev.v13@mail.ru",
    phone_number: "+7 900 000-00-13",
  },
  {
    client_id: 14,
    first_name: "Светлана",
    last_name: "Семёнова",
    middle_name: "Ильинична",
    email: "semenova.s14@mail.ru",
    phone_number: "+7 900 000-00-14",
  },
  {
    client_id: 15,
    first_name: "Роман",
    last_name: "Егоров",
    middle_name: "Дмитриевич",
    email: "egorov.r15@mail.ru",
    phone_number: "+7 900 000-00-15",
  },
  {
    client_id: 16,
    first_name: "Наталья",
    last_name: "Павлова",
    middle_name: "Анатольевна",
    email: "pavlova.n16@mail.ru",
    phone_number: "+7 900 000-00-16",
  },
  {
    client_id: 17,
    first_name: "Кирилл",
    last_name: "Козлов",
    middle_name: "Евгеньевич",
    email: "kozlov.k17@mail.ru",
    phone_number: "+7 900 000-00-17",
  },
  {
    client_id: 18,
    first_name: "Виктория",
    last_name: "Степанова",
    middle_name: "Олеговна",
    email: "stepanova.v18@mail.ru",
    phone_number: "+7 900 000-00-18",
  },
  {
    client_id: 19,
    first_name: "Глеб",
    last_name: "Николаев",
    middle_name: "Аркадьевич",
    email: "nikolaev.g19@mail.ru",
    phone_number: "+7 900 000-00-19",
  },
  {
    client_id: 20,
    first_name: "Людмила",
    last_name: "Орлова",
    middle_name: "Ивановна",
    email: "orlova.l20@mail.ru",
    phone_number: "+7 900 000-00-20",
  },
  {
    client_id: 21,
    first_name: "Тимофей",
    last_name: "Макаров",
    middle_name: "Сергеевич",
    email: "makarov.t21@mail.ru",
    phone_number: "+7 900 000-00-21",
  },
  {
    client_id: 22,
    first_name: "Ксения",
    last_name: "Захарова",
    middle_name: "Дмитриевна",
    email: "zakharova.k22@mail.ru",
    phone_number: "+7 900 000-00-22",
  },
  {
    client_id: 23,
    first_name: "Богдан",
    last_name: "Беляев",
    middle_name: "Андреевич",
    email: "belyaev.b23@mail.ru",
    phone_number: "+7 900 000-00-23",
  },
  {
    client_id: 24,
    first_name: "Диана",
    last_name: "Соловьёва",
    middle_name: "Романовна",
    email: "solovieva.d24@mail.ru",
    phone_number: "+7 900 000-00-24",
  },
  {
    client_id: 25,
    first_name: "Станислав",
    last_name: "Тарасов",
    middle_name: "Игоревич",
    email: "tarasov.s25@mail.ru",
    phone_number: "+7 900 000-00-25",
  },
  {
    client_id: 26,
    first_name: "Полина",
    last_name: "Гусева",
    middle_name: "Петровна",
    email: "guseva.p26@mail.ru",
    phone_number: "+7 900 000-00-26",
  },
  {
    client_id: 27,
    first_name: "Арсений",
    last_name: "Комаров",
    middle_name: "Никитич",
    email: "komarov.a27@mail.ru",
    phone_number: "+7 900 000-00-27",
  },
  {
    client_id: 28,
    first_name: "Вероника",
    last_name: "Фролова",
    middle_name: "Алексеевна",
    email: "frolova.v28@mail.ru",
    phone_number: "+7 900 000-00-28",
  },
  {
    client_id: 29,
    first_name: "Матвей",
    last_name: "Баранов",
    middle_name: "Владиславович",
    email: "baranov.m29@mail.ru",
    phone_number: "+7 900 000-00-29",
  },
  {
    client_id: 30,
    first_name: "Яна",
    last_name: "Тимофеева",
    middle_name: "Евгеньевна",
    email: "timofeeva.y30@mail.ru",
    phone_number: "+7 900 000-00-30",
  },
  {
    client_id: 31,
    first_name: "Георгий",
    last_name: "Григорьев",
    middle_name: "Михайлович",
    email: "grigoriev.g31@mail.ru",
    phone_number: "+7 900 000-00-31",
  },
  {
    client_id: 32,
    first_name: "Алина",
    last_name: "Крылова",
    middle_name: "Игоревна",
    email: "krylova.a32@mail.ru",
    phone_number: "+7 900 000-00-32",
  },
  {
    client_id: 33,
    first_name: "Лев",
    last_name: "Мельников",
    middle_name: "Сергеевич",
    email: "melnikov.l33@mail.ru",
    phone_number: "+7 900 000-00-33",
  },
  {
    client_id: 34,
    first_name: "Карина",
    last_name: "Давыдова",
    middle_name: "Андреевна",
    email: "davydova.k34@mail.ru",
    phone_number: "+7 900 000-00-34",
  },
  {
    client_id: 35,
    first_name: "Егор",
    last_name: "Жуков",
    middle_name: "Павлович",
    email: "zhukov.e35@mail.ru",
    phone_number: "+7 900 000-00-35",
  },
  {
    client_id: 36,
    first_name: "Дарья",
    last_name: "Калинина",
    middle_name: "Романовна",
    email: "kalinina.d36@mail.ru",
    phone_number: "+7 900 000-00-36",
  },
  {
    client_id: 37,
    first_name: "Платон",
    last_name: "Исаев",
    middle_name: "Викторович",
    email: "isaev.p37@mail.ru",
    phone_number: "+7 900 000-00-37",
  },
  {
    client_id: 38,
    first_name: "София",
    last_name: "Чернова",
    middle_name: "Алексеевна",
    email: "chernova.s38@mail.ru",
    phone_number: "+7 900 000-00-38",
  },
  {
    client_id: 39,
    first_name: "Вячеслав",
    last_name: "Богданов",
    middle_name: "Ильич",
    email: "bogdanov.v39@mail.ru",
    phone_number: "+7 900 000-00-39",
  },
  {
    client_id: 40,
    first_name: "Милана",
    last_name: "Блинова",
    middle_name: "Сергеевна",
    email: "blinova.m40@mail.ru",
    phone_number: "+7 900 000-00-40",
  },
  {
    client_id: 41,
    first_name: "Руслан",
    last_name: "Киселёв",
    middle_name: "Дмитриевич",
    email: "kiselev.r41@mail.ru",
    phone_number: "+7 900 000-00-41",
  },
  {
    client_id: 42,
    first_name: "Инна",
    last_name: "Воробьёва",
    middle_name: "Владимировна",
    email: "vorobieva.i42@mail.ru",
    phone_number: "+7 900 000-00-42",
  },
  {
    client_id: 43,
    first_name: "Денис",
    last_name: "Савельев",
    middle_name: "Анатольевич",
    email: "savelev.d43@mail.ru",
    phone_number: "+7 900 000-00-43",
  },
  {
    client_id: 44,
    first_name: "Агата",
    last_name: "Романова",
    middle_name: "Егоровна",
    email: "romanova.a44@mail.ru",
    phone_number: "+7 900 000-00-44",
  },
  {
    client_id: 45,
    first_name: "Марк",
    last_name: "Андреев",
    middle_name: "Станиславович",
    email: "andreev.m45@mail.ru",
    phone_number: "+7 900 000-00-45",
  },
  {
    client_id: 46,
    first_name: "Валерия",
    last_name: "Тихонова",
    middle_name: "Игоревна",
    email: "tikhonova.v46@mail.ru",
    phone_number: "+7 900 000-00-46",
  },
  {
    client_id: 47,
    first_name: "Олег",
    last_name: "Коновалов",
    middle_name: "Петрович",
    email: "konovalov.o47@mail.ru",
    phone_number: "+7 900 000-00-47",
  },
  {
    client_id: 48,
    first_name: "Элина",
    last_name: "Королёва",
    middle_name: "Денисовна",
    email: "koroleva.e48@mail.ru",
    phone_number: "+7 900 000-00-48",
  },
  {
    client_id: 49,
    first_name: "Павел",
    last_name: "Громов",
    middle_name: "Артурович",
    email: "gromov.p49@mail.ru",
    phone_number: "+7 900 000-00-49",
  },
  {
    client_id: 50,
    first_name: "Злата",
    last_name: "Назарова",
    middle_name: "Викторовна",
    email: "nazarova.z50@mail.ru",
    phone_number: "+7 900 000-00-50",
  },
]);
