use('insurance')

db.t_agent.insertMany([
  {
    agent_id: 1,
    branch_id: 1,
    first_name: "Игорь",
    last_name: "Медведев",
    middle_name: "Сергеевич",
    email: "agent1@mail.ru",
    phone_number: "+7 910 000-00-01",
  },
  {
    agent_id: 2,
    branch_id: 1,
    first_name: "Нина",
    last_name: "Романенко",
    middle_name: "Андреевна",
    email: "agent2@mail.ru",
    phone_number: "+7 910 000-00-02",
  },
  {
    agent_id: 3,
    branch_id: 1,
    first_name: "Денис",
    last_name: "Борисов",
    middle_name: "Алексеевич",
    email: "agent3@mail.ru",
    phone_number: "+7 910 000-00-03",
  },
  {
    agent_id: 4,
    branch_id: 3,
    first_name: "Марина",
    last_name: "Трофимова",
    middle_name: "Олеговна",
    email: "agent4@mail.ru",
    phone_number: "+7 910 000-00-04",
  },
  {
    agent_id: 5,
    branch_id: 3,
    first_name: "Роман",
    last_name: "Горбунов",
    middle_name: "Дмитриевич",
    email: "agent5@mail.ru",
    phone_number: "+7 910 000-00-05",
  },
  {
    agent_id: 6,
    branch_id: 4,
    first_name: "Алина",
    last_name: "Сафонова",
    middle_name: "Викторовна",
    email: "agent6@mail.ru",
    phone_number: "+7 910 000-00-06",
  },
  {
    agent_id: 7,
    branch_id: 5,
    first_name: "Максим",
    last_name: "Котов",
    middle_name: "Сергеевич",
    email: "agent7@mail.ru",
    phone_number: "+7 910 000-00-07",
  },
  {
    agent_id: 8,
    branch_id: 5,
    first_name: "Юлия",
    last_name: "Мартынова",
    middle_name: "Андреевна",
    email: "agent8@mail.ru",
    phone_number: "+7 910 000-00-08",
  },
  {
    agent_id: 9,
    branch_id: 5,
    first_name: "Владислав",
    last_name: "Емельянов",
    middle_name: "Игоревич",
    email: "agent9@mail.ru",
    phone_number: "+7 910 000-00-09",
  },
  {
    agent_id: 10,
    branch_id: 5,
    first_name: "Оксана",
    last_name: "Герасимова",
    middle_name: "Павловна",
    email: "agent10@mail.ru",
    phone_number: "+7 910 000-00-10",
  },
  {
    agent_id: 11,
    branch_id: 6,
    first_name: "Артур",
    last_name: "Крылов",
    middle_name: "Сергеевич",
    email: "agent11@mail.ru",
    phone_number: "+7 910 000-00-11",
  },
  {
    agent_id: 12,
    branch_id: 6,
    first_name: "Татьяна",
    last_name: "Фомина",
    middle_name: "Дмитриевна",
    email: "agent12@mail.ru",
    phone_number: "+7 910 000-00-12",
  },
  {
    agent_id: 13,
    branch_id: 7,
    first_name: "Сергей",
    last_name: "Логинов",
    middle_name: "Алексеевич",
    email: "agent13@mail.ru",
    phone_number: "+7 910 000-00-13",
  },
  {
    agent_id: 14,
    branch_id: 8,
    first_name: "Виктория",
    last_name: "Агапова",
    middle_name: "Ильинична",
    email: "agent14@mail.ru",
    phone_number: "+7 910 000-00-14",
  },
  {
    agent_id: 15,
    branch_id: 8,
    first_name: "Павел",
    last_name: "Серов",
    middle_name: "Михайлович",
    email: "agent15@mail.ru",
    phone_number: "+7 910 000-00-15",
  },
  {
    agent_id: 16,
    branch_id: 8,
    first_name: "Дарья",
    last_name: "Прохорова",
    middle_name: "Владимировна",
    email: "agent16@mail.ru",
    phone_number: "+7 910 000-00-16",
  },
  {
    agent_id: 17,
    branch_id: 10,
    first_name: "Николай",
    last_name: "Филатов",
    middle_name: "Анатольевич",
    email: "agent17@mail.ru",
    phone_number: "+7 910 000-00-17",
  },
  {
    agent_id: 18,
    branch_id: 10,
    first_name: "Инна",
    last_name: "Щербакова",
    middle_name: "Романовна",
    email: "agent18@mail.ru",
    phone_number: "+7 910 000-00-18",
  },
  {
    agent_id: 19,
    branch_id: 11,
    first_name: "Евгений",
    last_name: "Орехов",
    middle_name: "Сергеевич",
    email: "agent19@mail.ru",
    phone_number: "+7 910 000-00-19",
  },
  {
    agent_id: 20,
    branch_id: 12,
    first_name: "Ксения",
    last_name: "Сорокина",
    middle_name: "Павловна",
    email: "agent20@mail.ru",
    phone_number: "+7 910 000-00-20",
  },
  {
    agent_id: 21,
    branch_id: 12,
    first_name: "Тимур",
    last_name: "Белов",
    middle_name: "Игоревич",
    email: "agent21@mail.ru",
    phone_number: "+7 910 000-00-21",
  },
  {
    agent_id: 22,
    branch_id: 13,
    first_name: "Светлана",
    last_name: "Галкина",
    middle_name: "Андреевна",
    email: "agent22@mail.ru",
    phone_number: "+7 910 000-00-22",
  },
  {
    agent_id: 23,
    branch_id: 13,
    first_name: "Михаил",
    last_name: "Капустин",
    middle_name: "Дмитриевич",
    email: "agent23@mail.ru",
    phone_number: "+7 910 000-00-23",
  },
  {
    agent_id: 24,
    branch_id: 13,
    first_name: "Вероника",
    last_name: "Зотова",
    middle_name: "Алексеевна",
    email: "agent24@mail.ru",
    phone_number: "+7 910 000-00-24",
  },
  {
    agent_id: 25,
    branch_id: 14,
    first_name: "Олег",
    last_name: "Поляков",
    middle_name: "Викторович",
    email: "agent25@mail.ru",
    phone_number: "+7 910 000-00-25",
  },
]);
